#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: MergeMasterToTest

on:
  schedule:
    - cron: 00 */1 * * *
  push:
     branches: 
       - master

jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: test
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "hue715@gmail.com"
        git config --global user.name "hue715"
    - name: Load upstream commits
      run: |
        git pull https://github.com/coolsnowwolf/packages.git --no-edit

    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: test
      run: git push origin $DOWNSTREAM_BRANCH
